/*
 * FILE: prtosconf.h
 *
 * RISC-V 64-bit config parameters
 *
 * www.prtos.org
 */

#ifndef _PRTOS_ARCH_PRTOSCONF_H_
#define _PRTOS_ARCH_PRTOSCONF_H_

#define PRTOS_HM_EV_RISCV_ILLEGAL_INSTR      (PRTOS_HM_MAX_GENERIC_EVENTS + 0)
#define PRTOS_HM_EV_RISCV_INSTR_ACCESS_FAULT (PRTOS_HM_MAX_GENERIC_EVENTS + 1)
#define PRTOS_HM_EV_RISCV_LOAD_ACCESS_FAULT  (PRTOS_HM_MAX_GENERIC_EVENTS + 2)
#define PRTOS_HM_EV_RISCV_STORE_ACCESS_FAULT (PRTOS_HM_MAX_GENERIC_EVENTS + 3)
#define PRTOS_HM_EV_RISCV_INSTR_PAGE_FAULT   (PRTOS_HM_MAX_GENERIC_EVENTS + 4)
#define PRTOS_HM_EV_RISCV_LOAD_PAGE_FAULT    (PRTOS_HM_MAX_GENERIC_EVENTS + 5)
#define PRTOS_HM_EV_RISCV_STORE_PAGE_FAULT   (PRTOS_HM_MAX_GENERIC_EVENTS + 6)
#define PRTOS_HM_EV_RISCV_INSTR_MISALIGNED   (PRTOS_HM_MAX_GENERIC_EVENTS + 7)
#define PRTOS_HM_EV_RISCV_LOAD_MISALIGNED    (PRTOS_HM_MAX_GENERIC_EVENTS + 8)

#define PRTOS_HM_MAX_EVENTS (PRTOS_HM_MAX_GENERIC_EVENTS + 9)

struct prtos_conf_hyp_arch {};

struct prtos_conf_part_arch {};

struct prtos_conf_io_port {
    prtos_u32_t map[2048];
};

#endif
