/* This file is automatically generated.  Do not edit. */
#ifndef _SELINUX_FLASK_H_
#define _SELINUX_FLASK_H_

#if defined(__XEN__) || defined(__XEN_TOOLS__)

/*
 * Security object class definitions
 */
#define SECCLASS_XEN                                     1
#define SECCLASS_XEN2                                    2
#define SECCLASS_DOMAIN                                  3
#define SECCLASS_DOMAIN2                                 4
#define SECCLASS_HVM                                     5
#define SECCLASS_MMU                                     6
#define SECCLASS_RESOURCE                                7
#define SECCLASS_SHADOW                                  8
#define SECCLASS_EVENT                                   9
#define SECCLASS_GRANT                                   10
#define SECCLASS_SECURITY                                11
#define SECCLASS_VERSION                                 12
#define SECCLASS_ARGO                                    13

/*
 * Security identifier indices for initial entities
 */
#define SECINITSID_XENBOOT                              1
#define SECINITSID_XEN                                  2
#define SECINITSID_DOM0                                 3
#define SECINITSID_DOMIO                                4
#define SECINITSID_DOMXEN                               5
#define SECINITSID_UNLABELED                            6
#define SECINITSID_SECURITY                             7
#define SECINITSID_IOPORT                               8
#define SECINITSID_IOMEM                                9
#define SECINITSID_IRQ                                  10
#define SECINITSID_DEVICE                               11
#define SECINITSID_DOMU                                 12
#define SECINITSID_DOMDM                                13

#define SECINITSID_NUM                                  13

#endif /* __XEN__ || __XEN_TOOLS__ */

#endif
