/* This file is automatically generated.  Do not edit. */
static const char * const initial_sid_to_string[] =
{
    "null",
    "xenboot",
    "xen",
    "dom0",
    "domio",
    "domxen",
    "unlabeled",
    "security",
    "ioport",
    "iomem",
    "irq",
    "device",
    "domU",
    "domDM",
};

