/*
 * FILE: prtosconf.h
 *
 * Config parameters for both, PRTOS and partitions
 *
 * www.prtos.org
 */

#ifndef _PRTOS_ARCH_PRTOSCONF_H_
#define _PRTOS_ARCH_PRTOSCONF_H_

#define PRTOS_HM_EV_ARM_UNDEF_INSTR (PRTOS_HM_MAX_GENERIC_EVENTS + 0)
#define PRTOS_HM_EV_ARM_PREFETCH_ABORT (PRTOS_HM_MAX_GENERIC_EVENTS + 1)
#define PRTOS_HM_EV_ARM_DATA_ABORT (PRTOS_HM_MAX_GENERIC_EVENTS + 2)
#define PRTOS_HM_EV_ARM_DATA_ALIGNMENT_FAULT (PRTOS_HM_MAX_GENERIC_EVENTS + 3)
#define PRTOS_HM_EV_ARM_DATA_BACKGROUND_FAULT (PRTOS_HM_MAX_GENERIC_EVENTS + 4)
#define PRTOS_HM_EV_ARM_DATA_PERMISSION_FAULT (PRTOS_HM_MAX_GENERIC_EVENTS + 5)
#define PRTOS_HM_EV_ARM_INSTR_ALIGNMENT_FAULT (PRTOS_HM_MAX_GENERIC_EVENTS + 6)
#define PRTOS_HM_EV_ARM_INSTR_BACKGROUND_FAULT (PRTOS_HM_MAX_GENERIC_EVENTS + 7)
#define PRTOS_HM_EV_ARM_INSTR_PERMISSION_FAULT (PRTOS_HM_MAX_GENERIC_EVENTS + 8)

#define PRTOS_HM_MAX_EVENTS (PRTOS_HM_MAX_GENERIC_EVENTS + 9)

struct prtos_conf_hyp_arch {};

struct prtos_conf_part_arch {};

struct prtos_conf_io_port {
    prtos_u32_t map[2048];
};

#endif
